### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by viharm** [xbrowsersync/api-docker#1]
I have installed the API service docker image as per the instructions on a VM. However when I access the endpoint with browser I encounter the following error.

```
404 page not found
```

**Comment by nero120** [comment]
@viharm what platform (and version) are you on (Win/Linux/etc)? Also please run the following commands in the directory containing the `docker-compose.yml` file and report back:

- `docker --version`
- `docker-compose --version`
- `docker ps`
- `docker-compose ps`

**Comment by akramer-zibra** [comment]
Same error here... origin is wrong API version set in the dockerfile: `ENV XBROWSERSYNC_API_VERSION 1.1.9` . There isn't such version tag in the api repository. Works with `1.1.8`

**Comment by nero120** [comment]
No response from author, closing.

**Comment by viharm** [comment]
@nero120 ,

Apologies for the lack of my response. I was distracted by some personal committments and I had also destroyed the VM. I have reinitialised the VM and the endpoint is accessible fo *xBrowserSync* v1.1.9.

Thank you.

**Comment by nero120** [comment]
No worries at all @viharm, I know how that works!! 🙇
