### ISSUE TITLE
Making backups from the docker server database

### ISSUE THREAD

**Issue by youknow16** [xbrowsersync/api-docker#10]
Is there a way to make automatic backups of the database itself?
I installed the server using docker.
Ideally, I want to put that in a script so that we can always have a backup of the database.
Thanks

**Comment by nero120** [comment]
Yes I use a daily cron job and the mongo shell to export the db to a file.

First, install `mongodb-org-shell`:

```
sudo apt-get install mongodb-org-shell
```

Next, you'll need to expose the mongodb port to your mongodb docker container. Change directory to where the `docker-compose.yml` file is stored, then modify the file adding:

```
ports:
  - "27017:27017"
```

to the `db` service, then run `docker-compose up -d` to re-create the changed container. Check you are able to use the mongo shell to connect to the db using the following command:

```
mongo [dbname] --host localhost --port 27017 --username [username] --password [password] --authenticationDatabase admin
```

Replace the `[tokens]` with your relevant values.

If that works you can then create your daily cron script called `backup-db` (or whatever name you want) to export the db:

```
sudo nano /etc/cron.daily/backup-db
```

Add the following to the script:

```
#!/bin/sh
mongodump --db [dbname] --host localhost --port 27017 --username [username] --password [password] --authenticationDatabase admin --archive=[pathtobackupfile]-`date +"%Y-%m-%d"`.gz --gzip --quiet
```

Replace the `[tokens]` with your relevant values. The `[pathtobackupfile]` token ends with `-`date +"%Y-%m-%d"`.gz` which will append the current date to the end of the filename.

You can run the script immediately with to check it works:

```
./etc/cron.daily/backup-db
```

You can then use the following command to restore the db from the backup file:

```
mongorestore --username [username] --password [password] --authenticationDatabase admin --verbose=5 --gzip --drop --archive=[pathtobackupfile]
```

Replace the `[tokens]` with your relevant values.

That's it!

**Comment by youknow16** [comment]
Thanks!
Everything worked excpet the last step!
I get this error:
```
2020-09-19T11:09:43.505-0500	writing xbrowsersync.bookmarks to archive '/home/user/BACKUP/XBrowserSync-2020-09-19.gz'
2020-09-19T11:09:43.505-0500	writing xbrowsersync.newsynclogs to archive '/home/user/BACKUP/XBrowserSync-2020-09-19.gz'
2020-09-19T11:09:43.609-0500	Failed: archive writer: error writing data for collection `xbrowsersync.bookmarks` to disk: error reading collection: Failed to parse: { find: "bookmarks", skip: 0, snapshot: true, $readPreference: { mode: "secondaryPreferred" }, $db: "xbrowsersync" }. Unrecognized field 'snapshot'. / Mux ending but selectCases still open 2
```

**Comment by nero120** [comment]
That happens when the versions of the shell and mongodb are different, try adding `--forceTableScan` to the `mongodump` command.
