### ISSUE TITLE
no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by Robin-Sch** [xBrowserSync/api-docker#14]
I'm trying to run this on my raspberry pi (3), but there is no armv7 version for mongo available. How could I fix this?

**Comment by nero120** [comment]
There are no armv7 docker images available for mongodb. However, you can run a RP3 in ARMv8 mode, in which case you can use [this](https://hub.docker.com/r/arm64v8/mongo/) image. I think that's your only option.
