### ISSUE TITLE
Install docker production-ready without errors, but browser throws SSL error

### ISSUE THREAD

**Issue by nagyrobi** [xBrowserSync/api-docker#20]
Similar to https://github.com/xbrowsersync/api-docker/issues/19, but worse:

1. Install docker production-ready service OK (Ubuntu 20.04 LTS)
2. Edit .env (API_HOSTNAME=sync.internal.lan)
3. Add dns record to my internal DNS (sync.internal.lan), hostname resolving fine for any clients
4. docker-compose up -d without errors
5. On client workstation go to https://sync.internal.lan

Firefox error code: `SSL_ERROR_INTERNAL_ERROR_ALERT`
Chromium error code: `ERR_SSL_PROTOCOL_ERROR`

6. Tried with http only but it gets redirected automatically to https. (whouldn't mind plain http either, as I will only be using this within local LAN or VPN).

**Comment by nagyrobi** [comment]
Adding
```
    ports:
      - "8080:8080"
```
to the `api:` section of `docker-compose.yml` exposes port 8080 or the API directly, and I can connect with my browser extensions to that, but not with the Android app (see https://github.com/xbrowsersync/app/issues/356)

**Comment by nero120** [comment]
The production-ready docker compose file uses [caddy](https://github.com/caddyserver/caddy) as the reverse proxy and for handling SSL. I'm sorry but I do not have time to resolve environment-specific issues, please seek help in their repo.

**Comment by nagyrobi** [comment]
Well this should be specified in the documentation, as the user has the impression that by `production-ready`, following the exact steps described, he will get a system up and running, which is not the case.

There may be extra steps to be taken related to caddy, but not a single mention is made about that. And at the caddy repo, they don't know what are xbrowsersync's specific requirements, they can't be generic...

**Comment by nero120** [comment]
Well you shouldn't be using open source software that you are not paying for then should you? I am not first line support for some product. It should be pretty obvious that you need to bring some common sense to the table.
