### ISSUE TITLE
Increase max sync size

### ISSUE THREAD

**Issue by MrVrops** [xBrowserSync/api-docker#28]
Hello everyone, how can I increase the maximum sync size with a docker installation?

Thanks for everything

**Comment by nero120** [comment]
Assuming you are running the [production ready service](https://github.com/xbrowsersync/api-docker#running-a-production-ready-service), see step 3 of the [README](https://github.com/xbrowsersync/api-docker/blob/master/README.md):

_Open the [settings.json](https://github.com/xbrowsersync/api-docker/blob/master/settings.json) file and include any custom [settings](https://github.com/xbrowsersync/api#4-modify-configuration-settings) values you wish to run on your service. Important: do not change the db.host value._

You need to add `maxSyncSize` to `settings.json` and set it to the desired number in bytes. Once you've done that, in a terminal cd to the directory that you cloned the api-docker repo to and run:

```
docker-compose restart api
```

**Comment by MrVrops** [comment]
Thanks for you answer.
