### ISSUE TITLE
Not existing API version in dockerfile

### ISSUE THREAD

**Issue by akramer-zibra** [xbrowsersync/api-docker#3]
It occures an error while building the docker image from the dockerfile in this repo. It sets a wrong API version: `ENV XBROWSERSYNC_API_VERSION 1.1.9`. There doesn't exist such tagged version in the api repo. Should be `1.1.8`

**Comment by nero120** [comment]
Apologies, I had to back out the 1.1.9 release due to a late issue (always the way). The issue is resolved and I've released [v1.1.9](https://github.com/xbrowsersync/api/releases/tag/v1.1.9) now so you should now be able to build the dockerfile.

**Comment by akramer-zibra** [comment]
Great! Thank you very much
