### ISSUE TITLE
Running it behind Apache and as sub url?

### ISSUE THREAD

**Issue by gerroon** [xbrowsersync/api-docker#6]
Hi

Is it possible to reverse proxy it with Apache and run it under the room domain as a sub url? I do not use Traefik and I would like to give this a try with my existing setup if possible.

thanks

**Comment by nero120** [comment]
Hi @gerroon, yes definitely. Though I'm not an Apache user so you'd have to write the Apache site config file yourself. Just remove traefik from the docker-compose.yml file, then you can just point your existing Apache config to the xBrowserSync node service to use it as a reverse proxy to expose the service externally. Hope that helps!

**Comment by gerroon** [comment]
thanks I will try it
