### ISSUE TITLE
Docker image - change ports

### ISSUE THREAD

**Issue by policeman16** [xbrowsersync/api-docker#8]
Hi!

I'm trying to run private xbrowsersync API but I have one problem with docker-image. On the same server I have other service on 80 and 443 ports. How can I change ports of xbrowsersync's docker-compose?

**Comment by nero120** [comment]
@policeman16 you'll need to update the [traefik.toml](https://github.com/xbrowsersync/api-docker/blob/master/traefik.toml) file which is the config file for the reverse proxy (Traefik).

**Comment by policeman16** [comment]
@nero120 but after that still I cannot connect to my domain. Could you give me more details? Where and what should I change and what I need to write in plugin settings to connect with custom service?

**Comment by nero120** [comment]
@policeman16 go read the [traefik](https://docs.traefik.io/v1.7/) docs to understand how to customise the reverse proxy ports.
